apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-app
  namespace: example
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: "manthesh/example-app:${VERSION}"
        ports:
          - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: example-app
  namespace: example
spec:
  selector:
    app: example-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 9090
    port: 9090
